#
# Index config file for gh-archive dataset.
#

version: 0

index_id: quickwit-kafka

doc_mapping:
  field_mappings:
    - name: method
      type: text
      tokenizer: default
      record: position
    - name: url
      type: text
      tokenizer: default
      record: position
    - name: request
      type: text
      tokenizer: default
      record: position
    - name: response
      type: text
      tokenizer: default
      record: position
    - name: status
      type: text
      tokenizer: default
      record: position
    - name: timestamp
      type: text
      tokenizer: default
      record: position
    - name: duration
      type: text
      tokenizer: default
      record: position

search_settings:
  default_search_fields: [url, request, response]
