#
# Source config file.
#

sources:
 - fetch: fetch-kafka
   source_type: kafka
   params:
     topic: quickwit-kafka
     client_params:
       bootstrap.servers: kafka-1.kafka-headless.db.svc.cluster.local:9092
       group.id: fetch-consumer
       # security.protocol: SSL
 - graphql: graphql-kafka
   source_type: kafka
   params:
     topic: quickwit-kafka
     client_params:
       bootstrap.servers: kafka-1.kafka-headless.db.svc.cluster.local:9092
       group.id: graphql-consumer
       # security.protocol: SSL
 - graphql: graphql-pageevent
   source_type: kafka
   params:
     topic: quickwit-kafka
     client_params:
       bootstrap.servers: kafka-1.kafka-headless.db.svc.cluster.local:9092
       group.id: pageevent-consumer
       # security.protocol: SSL
